Missing match in regex
Previously, got:

    Error: 'wget -q -O - https://www.kernel.org/pub/linux/utils/boot/syslinux/.xx/syslinux-6.03.tar.gz | tar -xzf - -C `dirname /usr/local/src/syslinux-6.03`' returned 2 instead of one of [0]